version: '3'

networks:
  my-network:
    external: true
volumes:
  cache:
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  #nginx
  nginx:
    build: etc/nginx
    container_name: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - php-fpm
      - store_goshop
      - store_tiendasupervielle
      - store_icbc
      #new_services
    volumes:
      - cache:/var/cache
      - ./etc/ssl:/etc/ssl
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/nginx.conf.default:/etc/nginx/conf.d/default.conf
      - ./etc/nginx/sites-available:/etc/nginx/sites-enabled
      - ./includes:/etc/nginx/includes/
      - ./templates/backend-not-found.html:/var/www/html/backend-not-found.html
      - ./logs:/var/log/nginx
      - ./www_tiendaclic:/var/www/html/www_tiendaclic
      - ./www_goshop:/var/www/html/www_goshop
      - ./www_tiendasupervielle:/var/www/html/www_tiendasupervielle
      - ./www_icbc:/var/www/html/www_icbc
      #new_volumens
    networks:
      - my-network
  php-fpm:
    build: etc/php
    container_name: php-fpm
    restart: always
    volumes:
      - ./cache:/var/cache
      - ./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./etc/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./www_tiendaclic:/var/www/html/www_tiendaclic
      - ./www_goshop:/var/www/html/www_goshop
      - ./www_tiendasupervielle:/var/www/html/www_tiendasupervielle
      - ./www_icbc:/var/www/html/www_icbc
      #new_volumens
    networks:
      - my-network
  #Proyects
  store_tiendaclic:
    image: tianon/true #minimal image
    depends_on:
      - php-fpm
    working_dir: /var/www/html/www_tiendaclic
    networks:
      - my-network
  store_goshop:
    image: tianon/true #minimal image
    depends_on:
      - php-fpm
    working_dir: /var/www/html/www_goshop
    networks:
      - my-network
  store_tiendasupervielle:
    image: tianon/true #minimal image
    depends_on:
      - php-fpm
    working_dir: /var/www/html/www_tiendasupervielle
    networks:
      - my-network
  store_icbc:
    image: tianon/true #minimal image
    depends_on:
      - php-fpm
    working_dir: /var/www/html/www_icbc
    networks:
      - my-network