version: '3'

networks:
  dockernet:
    external: true

services:
  # nginx
  web:
    build: ./etc/nginx
    depends_on:
      - mysqldb
      #new_services
    restart: always
    volumes:
      - ./etc/ssl:/etc/ssl
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/sites-available:/etc/nginx/sites-enabled
      - ./includes:/etc/nginx/includes/
      - ./backend-not-found.html:/var/www/html/backend-not-found.html
      - ./logs:/var/log/nginx
      #new_volumens
    ports:
      ## for development only
      - 80:80
      - 443:443
    networks:
      - dockernet
    #command: bash -c "ln -sf /etc/nginx/sites-available/* /etc/nginx/sites-enabled/"
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
  # visualizer
  visualizer:
    image: dockersamples/visualizer
    deploy:
      placement:
        constraints:
          - node.role == manager
    ## NOTE: you may want to add more security features to prevent easy access on production
    ports:
      - 9999:8080
  # databases
  mysqldb:
    image: mysql:5.7
    restart: always
    ports:
      - 3000:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: stores
      MYSQL_PASSWORD: stores
    volumes:
      - ./mysqldb:/var/lib/mysql
    networks:
      - dockernet
  php-fpm:
    build: etc/php
    restart: always
    volumes:
      - ./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./etc/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      #new_volumens
    depends_on:
      - mysqldb
    networks:
      - dockernet
  # Proyects