version: '3'

networks:
  my-network:
    external: true
volumes:
  cache:
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  #nginx
  _NGINX_:
    build: etc/nginx
    container_name: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - php-fpm
      #new_services
    volumes:
      - cache:/var/cache
      - ./etc/ssl:/etc/ssl
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/nginx.conf.default:/etc/nginx/conf.d/default.conf
      - ./etc/nginx/sites-available:/etc/nginx/sites-enabled
      - ./includes:/etc/nginx/includes/
      - ./templates/backend-not-found.html:/var/www/html/backend-not-found.html
      - ./logs:/var/log/nginx
      #new_volumens
    networks:
      - my-network
  _PHPFPM_:
    build: etc/php
    container_name: php-fpm
    restart: always
    volumes:
      - ./cache:/var/cache
      - ./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./etc/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      #new_volumens
    networks:
      - my-network
  #Proyects