version: '3'

networks:
  dockernet:
    external: true
volumes:
  cache:
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  #nginx
  nginx:
    build: etc/nginx
    container_name: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - mysqldb
      - php-fpm
      - store_spv-store
      - store_tclic-store
      #new_services
    volumes:
      - cache:/var/cache
      - ./etc/ssl:/etc/ssl
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/nginx.conf.default:/etc/nginx/conf.d/default.conf
      - ./etc/nginx/sites-available:/etc/nginx/sites-enabled
      - ./includes:/etc/nginx/includes/
      - ./templates/backend-not-found.html:/var/www/html/backend-not-found.html
      - ./logs:/var/log/nginx
      - ./www_spv-store:/var/www/html/www_spv-store
      - ./www_tclic-store:/var/www/html/www_tclic-store
      #new_volumens
    networks:
      - dockernet
  # databases
  mysqldb:
    build: etc/mysql
    container_name: mysqldb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysqldb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
    ports:
      - '3000:3306'
    networks:
      - dockernet
  php-fpm:
    build: etc/php
    container_name: php-fpm
    restart: always
    volumes:
      - ./cache:/var/cache
      - ./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./etc/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./www_spv-store:/var/www/html/www_spv-store
      - ./www_tclic-store:/var/www/html/www_tclic-store
      #new_volumens
    depends_on:
      - mysqldb
    networks:
      - dockernet
  #Proyects
  store_spv-store:
    image: tianon/true #minimal image
    depends_on:
      - php-fpm
      - mysqldb
    working_dir: /var/www/html/www_spv-store
    networks:
      - dockernet
  store_tclic-store:
    image: tianon/true #minimal image
    depends_on:
      - php-fpm
      - mysqldb
    working_dir: /var/www/html/www_tclic-store
    networks:
      - dockernet