version: '3'

networks:
  dockernet:
    external: true
volumes:
  cache:
    driver_opts:
      type: tmpfs
      device: tmpfs

services:
  #nginx
  nginx:
    image: lagun4ik/nginx-pagespeed
    restart: always
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - mysqldb
      - store_icbc
      #new_services
    volumes:
      - cache:/var/cache/ngx_pagespeed
      - cache:/var/cache
      - ./etc/ssl:/etc/ssl
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/nginx.conf.default:/etc/nginx/nginx.conf.default
      - ./etc/nginx/sites-available:/etc/nginx/sites-enabled
      - ./includes:/etc/nginx/includes/
      - ./templates/backend-not-found.html:/var/www/html/backend-not-found.html
      - ./logs:/var/log/nginx
      - ./www_icbc:/var/www/html/www_icbc
      #new_volumens
    networks:
      - dockernet
    #command: bash -c "rm /etc/nginx/nginx.conf"
  #visualizer
  visualizer:
    image: dockersamples/visualizer
    deploy:
      placement:
        constraints:
          - node.role == manager
    ## NOTE: you may want to add more security features to prevent easy access on production
    ports:
      - 9999:8080
  # databases
  mysqldb:
    image: mysql:5.7
    restart: always
    ports:
      - 3000:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: stores
      MYSQL_PASSWORD: stores
    volumes:
      - ./mysqldb:/var/lib/mysql
    networks:
      - dockernet
  php-fpm:
    build: ./etc/php
    restart: always
    volumes:
      - ./cache:/var/cache
      - ./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./etc/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./www_icbc:/var/www/html/www_icbc
      #new_volumens
    depends_on:
      - mysqldb
    networks:
      - dockernet
  #Proyects
  store_icbc:
    image: tianon/true #minimal image
    depends_on:
      - php-fpm
      - mysqldb
    working_dir: /var/www/html/www_icbc
    networks:
      - dockernet