version: '3'

networks:
  mynet:
    external: true

services:
  # nginx
  web:
    image: nginx
    depends_on:
      - mysqldb
      - store1
      - store2
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf
      - ./includes:/etc/nginx/includes/
      - ./backend-not-found.html:/var/www/html/backend-not-found.html
      - ./logs:/var/log/nginx
      - ./store1:/var/www/html/store1
      - ./store2:/var/www/html/store2
    ports:
      ## for development only
      - 80:80
      - 443:443
    networks:
      - mynet
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
  # visualizer
  visualizer:
    image: dockersamples/visualizer
    deploy:
      placement:
        constraints:
          - node.role == manager
    ## NOTE: you may want to add more security features to prevent easy access on production
    ports:
      - 9999:8080
  # databases
  mysqldb:
    image: mysql:5.7
    restart: always
    ports:
      - 3000:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: stores
      MYSQL_PASSWORD: stores
    volumes:
      - ./mysqldb:/var/lib/mysql
    networks:
      - mynet
  # Proyects
